### ISSUE TITLE
Suggestion: insert with random color?

### ISSUE THREAD

**Issue by tinchodias** [OpenSmock/Pyramid#12]
I can imagine the utility of inserting elements already with a color, so okay, but maybe you like the random option. In Pharo it's very simple to get one with the expression `Color random`.

<img width="451" alt="Screenshot 2023-07-05 at 12 44 44" src="https://github.com/OpenSmock/Pyramid/assets/3044265/8f69e171-bff6-49a9-ac75-5782fd00bc18">

**Comment by labordep** [comment]
Thanks for your feedback @tinchodias. 
We are in a reflexion phase for this panel. 
Actually this panel is temporary, just for the core development phase. 
In term, we plane to propose a lot of Bloc / Toplo elements in this panel, organized by Theme or functions with search capacities. 
For basic BlElement, to have a random color is a good idea to distinguate added elements by a color.
Concerning the panel closing, we think that this panel should be always open during its usage because by this way you can add multiple elements without re-click to open the panel. May be this can be a settings to manage this behavior but I think this is too much.

**Comment by tinchodias** [comment]
Great!
