### ISSUE TITLE
Export as Pharo code?

### ISSUE THREAD

**Issue by tinchodias** [OpenSmock/Pyramid#14]
Do you plan to add "Export as Pharo code"? I mean a snippet like script "space := BlSpace new. space addChild: (...)".

That's the first thing when I used this great tool. "Wow, it could help me to write examples e.g.  to share on an email or Discord".

**Comment by labordep** [comment]
Our principe is to save Pyramid project with pySTON (using [Bloc-Serialization](https://github.com/OpenSmock/Bloc-Serialization) project). This is a proposition to save a project.

@tinchodias do you mean that you want another way to save your project, as a source-code generation to recreate a Pyramid project instead of generate a pySTON in a method ? 

Or may be to have the pySTON code in the clipboard ?

**Comment by tinchodias** [comment]
Hi, yes, I was talking of a new format to export other than pyston

**Comment by labordep** [comment]
Ok ! 
We note to propose a new plugin to export as Pharo source-code.
We think this is more simple to do that in Pharo than others langage :D

**Comment by labordep** [comment]
@tinchodias this is done, if you want to try it and do feedbacks 😉
