### ISSUE TITLE
Element's margin and padding

### ISSUE THREAD

**Issue by tinchodias** [OpenSmock/Pyramid#15]
Do you plan to support them?

**Comment by labordep** [comment]
> 

You of course.
We are in reflexion about Layout : layout building API is not simple (this is normal because there are a lot of things that we can do). To propose a good user interface we need to take our time, we plane to start with your ProportionalLayout and also FlowLayout. 

We take a look at margin and padding, and we found that these properties don't works without Layout. Do you confirm ?

**Comment by tinchodias** [comment]
Please check https://github.com/pharo-graphics/Bloc/issues/272 maybe it answers!

**Comment by Nyan11** [comment]
https://github.com/OpenSmock/Pyramid/pull/55
