### ISSUE TITLE
Library to create Bloc elements & Toplo widgets

### ISSUE THREAD

**Issue by labordep** [OpenSmock/Pyramid#168]
Hi @Nyan11,
I'm considering the library panel for creating elements (when click on + button of the tree).
I would like to propose a similar architecture to the "Pharo Settings", based on a pragma in methods.

Thus, all declared pragma should offer contents for the library (or catalog) similar to how classes offer Settings content.
It can be provided by active plugins or static classes. I'm not sure, but I think using plugins is more coherent with Pyramid principles.

This content can be a tree organized as menu or Tree Settings with a dedicated structure.
We can start from actuel `PyramidLibraryElement` to add these features.

The need is: 
- To provide basics BlElements prepared with shapes or properties (text, square, circle, image, etc.)
- To offer Toplo Widgets, organized into categories (action, list, pane, etc.).

What is you opinion?

**Comment by Nyan11** [comment]
Currently, you have to write a BlocClosure that create a new BlElement to add it to the library list.

> based on a pragma in methods

We can also imagine a solution based on the subclasses of BlElement. I do not like the class solution because there is a lot of subclasses of BlElement. The pragma solution remove the need to have any plugins because the pragma will automatically be detected.

> It can be provided by active plugins or static classes.

plugins. This way we will have a plugin for Bloc and one for Toplo. Because Pragma are automatically detected, there will be a plugin that do not bring any modificaiton to Pyramid, it will just contains the Pragma for the library.

Later we could add a plugin with logos and icons.

> This content can be a tree organized as menu

We should brainstorm all the elements we need in the library, and then organize them. It will be easier to make the different section and decide if the catalog model is a tree, a list or something else.

**Comment by Nyan11** [comment]
We can even imagine a system where each plugins bring it's on catalog.
For example the BlocLibrary plugin will be a list and the ToploLibrary plugin will be a menu with different categories.

**Comment by Nyan11** [comment]
![image](https://github.com/OpenSmock/Pyramid/assets/34318678/77de4184-bd43-4208-adcb-3648c2c795e3)
